package usu.pajak.fariz.service;

import com.google.gson.Gson;
import com.itextpdf.io.font.constants.StandardFonts;
import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.borders.Border;
import com.itextpdf.layout.borders.DottedBorder;
import com.itextpdf.layout.borders.SolidBorder;
import com.itextpdf.layout.element.*;
import com.itextpdf.layout.property.*;
import usu.pajak.fariz.model.BuktiPotong;

import java.io.*;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;

public class PdfBuktiPotong {
    private DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();

    public static void main(String[] args) throws IOException {
        String response = ReceiveRka.getInstance.callApiUsu("http://localhost:8253/bukti_potong?user_id=1844&source_of_fund=NON-PNBP","GET");
        new PdfBuktiPotong().createPdfA1("/test7.pdf",new Gson().fromJson(response, BuktiPotong.class), 1844);
//        new PdfBuktiPotong().createPdf("/test7.pdf");
//        BigDecimal bd = new BigDecimal("700000000");
//
//        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
//        kursIndonesia.setMaximumFractionDigits(0);
//        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
//        formatRp.setCurrencySymbol("");
//        formatRp.setMonetaryDecimalSeparator(',');
//        formatRp.setGroupingSeparator('.');
//
//        kursIndonesia.setDecimalFormatSymbols(formatRp);
//        System.out.println(kursIndonesia.format(bd));
    }

    public PdfBuktiPotong(){
        kursIndonesia.setMaximumFractionDigits(0);
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
        formatRp.setCurrencySymbol("");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(formatRp);
    }

    public void createPdf(String dest) throws IOException {
        //Initialize PDF writer
        PdfWriter writer = new PdfWriter(dest);
        //Initialize PDF document
        PdfDocument pdf = new PdfDocument(writer);
        // Initialize document
        PageSize pageSize = PageSize.LEGAL;
        Document document = new Document(pdf, pageSize);
        document.setMargins(20, 20, 20, 20);
        PdfFont font = PdfFontFactory.createFont(StandardFonts.HELVETICA);
        PdfFont bold = PdfFontFactory.createFont(StandardFonts.HELVETICA_BOLD);

        Table mainTable = new Table(new float[]{1});
        mainTable.setWidth(UnitValue.createPercentValue(100));

        Cell s = new Cell();
        s.setBorder(Border.NO_BORDER);
        Table stable = new Table(new float[]{4,100,4});
        stable.setFixedLayout();
        stable.setWidth(UnitValue.createPercentValue(100));
        Cell x = new Cell();
        x.setHeight(4);
        x.add(new Paragraph(" "));
        x.setBackgroundColor(ColorConstants.BLACK);
        stable.addCell(x);
        x = new Cell();
        x.setBorder(Border.NO_BORDER);
        x.setBorderTop(new DottedBorder(1f));
        stable.addCell(x);
        x = new Cell();
        x.add(new Paragraph(" "));
        x.setBackgroundColor(ColorConstants.BLACK);
        stable.addCell(x);
        s.add(stable);
        mainTable.addCell(s);

        Cell h = new Cell();
        h.setBorder(Border.NO_BORDER);
        Table headerTable = new Table(new float[]{60,100,20,50});
        headerTable.setFixedLayout();
        headerTable.setWidth(UnitValue.createPercentValue(100));
        Cell c = new Cell(5,1);
        c.setBorderTop(Border.NO_BORDER);
        c.setBorderLeft(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.setHorizontalAlignment(HorizontalAlignment.CENTER);
        c.setVerticalAlignment(VerticalAlignment.MIDDLE);
        c.setFont(bold);
        c.setFontSize(9);
        c.add(new Image(ImageDataFactory.create("/logo_drijen_pajak.png")).scaleToFit(70,70).setTextAlignment(TextAlignment.CENTER).setHorizontalAlignment(HorizontalAlignment.CENTER));
        c.add(new Paragraph("\nKEMENTERIAN KEUANGAN RI DIREKTORAT JENDERAL PAJAK"));
        headerTable.addCell(c);
        c = new Cell(3,1);
        c.setTextAlignment(TextAlignment.CENTER);
        c.setBorderTop(Border.NO_BORDER);
        c.setFont(bold);
        c.setFontSize(11);
        c.add(new Paragraph("BUKTI POTONGAN PAJAK PENGHASILAN PASAL 21 BAGI PEGAWAI TETAP ATAU PENERIMA PENSIUN ATAU TUNJANGAN HARI TUA/JAMINAN HARI TUA BERKALA\n\n"));
        headerTable.addCell(c);
        c = new Cell(1,2);
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.RIGHT);
        c.setHorizontalAlignment(HorizontalAlignment.RIGHT);
        Table dum = new Table(new float[]{15,1,15,1,15,1,15});
        dum.setHorizontalAlignment(HorizontalAlignment.RIGHT);
        dum.setFixedLayout();
        Cell d = new Cell();
        d.add(new Paragraph("  "));
        d.setHeight(10);
        dum.addCell(d);
        d = new Cell();
        d.setBorder(Border.NO_BORDER);
        d.add(new Paragraph(""));
        dum.addCell(d);
        d = new Cell();
        d.add(new Paragraph("  "));
        d.setBackgroundColor(ColorConstants.BLACK);
        dum.addCell(d);
        d = new Cell();
        d.setBorder(Border.NO_BORDER);
        d.add(new Paragraph(""));
        dum.addCell(d);
        d = new Cell();
        d.add(new Paragraph("  "));
        dum.addCell(d);
        d = new Cell();
        d.setBorder(Border.NO_BORDER);
        d.add(new Paragraph(""));
        dum.addCell(d);
        d = new Cell();
        d.add(new Paragraph("  "));
        d.setBackgroundColor(ColorConstants.BLACK);
        dum.addCell(d);
        c.add(dum);
        headerTable.addCell(c);
        c = new Cell(1,2);
        c.setFont(bold);
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.RIGHT);
        c.add(new Paragraph("FORMULIR 1721 - A1"));
        headerTable.addCell(c);
        c = new Cell(1,2);
        c.setFontSize(7);
        c.setHorizontalAlignment(HorizontalAlignment.RIGHT);
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("Lembar ke-1 : untuk Penerima Penghasilan").setFirstLineIndent(30));
        c.add(new Paragraph("Lembar ke-2 : untuk Pemotong").setFirstLineIndent(30));
        headerTable.addCell(c);
        c = new Cell(2,2);
        c.setFont(bold);
        c.setVerticalAlignment(VerticalAlignment.MIDDLE);
        c.setTextAlignment(TextAlignment.JUSTIFIED);
        c.add(new Paragraph("NOMOR :    1 . 1 - 12 . 18 - 00000001").setFirstLineIndent(20));
        c.setFontSize(15);
        headerTable.addCell(c);
        c = new Cell();
        c.setFont(bold);
        c.setFontSize(8);
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.add(new Paragraph("MASA PEROLEHAN \nPENGHASILAN [mm - mm]"));
        headerTable.addCell(c);
        c = new Cell();
        c.setBorderTop(Border.NO_BORDER);
        c.setBorderRight(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.add(new Paragraph("01 - 12"));
        headerTable.addCell(c);

        h.add(headerTable);
        mainTable.addCell(h);
        document.add(mainTable);
        //Close document
        document.close();
    }

    public File createPdfA1(String dest, BuktiPotong buktiPotong, Integer userId) throws IOException {
        //Initialize PDF writer
        PdfWriter writer = new PdfWriter(dest);
        //Initialize PDF document
        PdfDocument pdf = new PdfDocument(writer);
        // Initialize document
        PageSize pageSize = PageSize.LEGAL;
        Document document = new Document(pdf, pageSize);
        document.setMargins(20, 20, 20, 20);
        PdfFont font = PdfFontFactory.createFont(StandardFonts.HELVETICA);
        PdfFont bold = PdfFontFactory.createFont(StandardFonts.HELVETICA_BOLD);

        Table mainTable = new Table(new float[]{1});
        mainTable.setWidth(UnitValue.createPercentValue(100));

        Cell s = new Cell();
        s.setBorder(Border.NO_BORDER);
        Table stable = new Table(new float[]{4,100,4});
        stable.setFixedLayout();
        stable.setWidth(UnitValue.createPercentValue(100));
        Cell x = new Cell();
        x.setHeight(4);
        x.add(new Paragraph(" "));
        x.setBackgroundColor(ColorConstants.BLACK);
        stable.addCell(x);
        x = new Cell();
        x.setBorder(Border.NO_BORDER);
        x.setBorderTop(new DottedBorder(1f));
        stable.addCell(x);
        x = new Cell();
        x.add(new Paragraph(" "));
        x.setBackgroundColor(ColorConstants.BLACK);
        stable.addCell(x);
        s.add(stable);
        mainTable.addCell(s);

        Cell h = new Cell();
        h.setBorder(Border.NO_BORDER);
        Table headerTable = new Table(new float[]{60,100,20,50});
        headerTable.setFixedLayout();
        headerTable.setWidth(UnitValue.createPercentValue(100));
        Cell c = new Cell(5,1);
        c.setBorderTop(Border.NO_BORDER);
        c.setBorderLeft(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.setHorizontalAlignment(HorizontalAlignment.CENTER);
        c.setVerticalAlignment(VerticalAlignment.MIDDLE);
        c.setFont(bold);
        c.setFontSize(9);
        c.add(new Image(ImageDataFactory.create("/logo_drijen_pajak.png")).scaleToFit(70,70).setTextAlignment(TextAlignment.CENTER).setHorizontalAlignment(HorizontalAlignment.CENTER));
        c.add(new Paragraph("\nKEMENTERIAN KEUANGAN RI DIREKTORAT JENDERAL PAJAK"));
        headerTable.addCell(c);
        c = new Cell(3,1);
        c.setTextAlignment(TextAlignment.CENTER);
        c.setBorderTop(Border.NO_BORDER);
        c.setFont(bold);
        c.setFontSize(11);
        c.add(new Paragraph("BUKTI POTONGAN PAJAK PENGHASILAN PASAL 21 BAGI PEGAWAI TETAP ATAU PENERIMA PENSIUN ATAU TUNJANGAN HARI TUA/JAMINAN HARI TUA BERKALA\n\n"));
        headerTable.addCell(c);
        c = new Cell(1,2);
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.RIGHT);
        c.setHorizontalAlignment(HorizontalAlignment.RIGHT);
        Table dum = new Table(new float[]{15,1,15,1,15,1,15});
        dum.setHorizontalAlignment(HorizontalAlignment.RIGHT);
        dum.setFixedLayout();
        Cell d = new Cell();
        d.add(new Paragraph("  "));
        d.setHeight(10);
        dum.addCell(d);
        d = new Cell();
        d.setBorder(Border.NO_BORDER);
        d.add(new Paragraph(""));
        dum.addCell(d);
        d = new Cell();
        d.add(new Paragraph("  "));
        d.setBackgroundColor(ColorConstants.BLACK);
        dum.addCell(d);
        d = new Cell();
        d.setBorder(Border.NO_BORDER);
        d.add(new Paragraph(""));
        dum.addCell(d);
        d = new Cell();
        d.add(new Paragraph("  "));
        dum.addCell(d);
        d = new Cell();
        d.setBorder(Border.NO_BORDER);
        d.add(new Paragraph(""));
        dum.addCell(d);
        d = new Cell();
        d.add(new Paragraph("  "));
        d.setBackgroundColor(ColorConstants.BLACK);
        dum.addCell(d);
        c.add(dum);
        headerTable.addCell(c);
        c = new Cell(1,2);
        c.setFont(bold);
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.RIGHT);
        c.add(new Paragraph("FORMULIR 1721 - A1"));
        headerTable.addCell(c);
        c = new Cell(1,2);
        c.setFontSize(7);
        c.setHorizontalAlignment(HorizontalAlignment.RIGHT);
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("Lembar ke-1 : untuk Penerima Penghasilan").setFirstLineIndent(30));
        c.add(new Paragraph("Lembar ke-2 : untuk Pemotong").setFirstLineIndent(30));
        headerTable.addCell(c);
        c = new Cell(2,2);
        c.setFont(bold);
        c.setVerticalAlignment(VerticalAlignment.MIDDLE);
        c.setTextAlignment(TextAlignment.JUSTIFIED);
//        c.add(new Paragraph("NOMOR :    1 . 1 - 12 . 19 - "+String.format("%07d", userId)).setFirstLineIndent(20));
        c.add(new Paragraph("NOMOR :    1 . 1 - 12 . 19 - "+buktiPotong.getH_01()).setFirstLineIndent(20));
        c.setFontSize(15);
        headerTable.addCell(c);
        c = new Cell();
        c.setFont(bold);
        c.setFontSize(8);
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.add(new Paragraph("MASA PEROLEHAN \nPENGHASILAN [mm - mm]"));
        headerTable.addCell(c);
        c = new Cell();
        c.setBorderTop(Border.NO_BORDER);
        c.setBorderRight(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.add(new Paragraph("01 - 12"));
        headerTable.addCell(c);

        h.add(headerTable);
        mainTable.addCell(h);

        Cell pemotong = new Cell();
        Table pemotongTable = new Table(new float[]{1,1,4,1,3,1,3,5});
//        pemotongTable.setWidth(UnitValue.createPercentValue(100));
        Cell p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph("NPWP PEMOTONG"));
        p.setFont(bold);
        p.setFontSize(8);
        pemotongTable.addCell(p);
        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph(":   "));
        p.setFont(bold);
        p.setFontSize(8);
        pemotongTable.addCell(p);
        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        p.setTextAlignment(TextAlignment.CENTER);
        p.add(new Paragraph(buktiPotong.getH_03()[0]));
        p.setFontSize(10);
        pemotongTable.addCell(p);
        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph("-"));
        p.setWidth(3);
        p.setFont(bold);
        p.setFontSize(8);
        pemotongTable.addCell(p);
        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        p.setWidth(100);
        p.setTextAlignment(TextAlignment.CENTER);
        p.add(new Paragraph(buktiPotong.getH_03()[1]));
        p.setFontSize(10);
        pemotongTable.addCell(p);
        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph("."));
        p.setWidth(3);
        p.setFont(bold);
        p.setFontSize(8);
        pemotongTable.addCell(p);
        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        p.setTextAlignment(TextAlignment.CENTER);
        p.add(new Paragraph(buktiPotong.getH_03()[2]));
        p.setFontSize(10);
        pemotongTable.addCell(p);
        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph(""));
        pemotongTable.addCell(p);
        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph("NAMA PEMOTONG"));
        p.setFont(bold);
        p.setFontSize(8);
        pemotongTable.addCell(p);
        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph(":   "));
        p.setFont(bold);
        p.setFontSize(8);
        pemotongTable.addCell(p);
        p = new Cell(1,6);
        p.setBorder(Border.NO_BORDER);
        p.setWidth(450);
        p.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        p.add(new Paragraph(buktiPotong.getH_04()));
        p.setFontSize(10);
        pemotongTable.addCell(p);

        pemotong.add(pemotongTable);
        mainTable.addCell(pemotong);

        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph("\n"));
        p.setFont(bold);
        p.setFontSize(1);
        mainTable.addCell(p);

        Cell sectionA = new Cell();
        sectionA.setBorder(Border.NO_BORDER);
        sectionA.add(new Paragraph("A. IDENTITAS PENERIMA PENGHASILAN YANG DIPOTONG"));
        sectionA.setFont(bold);
        sectionA.setFontSize(9);
        mainTable.addCell(sectionA);

        sectionA = new Cell();
        Table sectionATable = new Table(
                new float[]{6,28,3,10,30,10,30,15,1,5,10,15,4,10,10,4,10,10,5});
        sectionATable.setFixedLayout();
        sectionATable.setWidth(UnitValue.createPercentValue(100));
        Cell a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("1."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("NPWP"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(":  "));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell(1, 5);
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(buktiPotong.getA_01()).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        a.setFontSize(10);
        sectionATable.addCell(a);
//        a = new Cell();
//        a.setBorder(Border.NO_BORDER);
//        a.add(new Paragraph("-"));
//        a.setFont(bold);
//        a.setFontSize(10);
//        sectionATable.addCell(a);
//        a = new Cell();
//        a.setBorder(Border.NO_BORDER);
//        a.add(new Paragraph("121    ").setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
//        a.setFontSize(10);
//        sectionATable.addCell(a);
//        a = new Cell();
//        a.setBorder(Border.NO_BORDER);
//        a.add(new Paragraph("."));
//        a.setFont(bold);
//        a.setFontSize(10);
//        sectionATable.addCell(a);
//        a = new Cell();
//        a.setBorder(Border.NO_BORDER);
//        a.add(new Paragraph("000").setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
//        a.setFontSize(10);
//        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("6."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell(1,9);
        a.setBorder(Border.NO_BORDER);
        a.setFont(bold);
        a.setFontSize(8);
        a.add(new Paragraph("STATUS / JUMLAH TANGGUNGAN KELUARGA UNTUK PTKP"));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("2."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("NIK/NO.PASPOR"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(":  "));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell(1,5);
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(buktiPotong.getA_02()).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(""));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("K/"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.setTextAlignment(TextAlignment.CENTER);
        if(buktiPotong.getA_07() == null)
            a.add(new Paragraph("   "));
        else
            a.add(new Paragraph(buktiPotong.getA_07().toString()));
        a.setFontSize(10);
        a.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("TK/"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.setTextAlignment(TextAlignment.CENTER);
        if(buktiPotong.getA_08() == null)
            a.add(new Paragraph("   "));
        else
            a.add(new Paragraph(buktiPotong.getA_08().toString()));
        a.setFontSize(10);
        a.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("HB/"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setTextAlignment(TextAlignment.CENTER);
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        a.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("3."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("NAMA"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(":  "));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell(1,5);
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(buktiPotong.getA_03()).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("7."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell(1,3);
        a.setBorder(Border.NO_BORDER);
        a.setFont(bold);
        a.setFontSize(8);
        a.add(new Paragraph("NAMA JABATAN"));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.setFont(bold);
        a.setFontSize(8);
        a.add(new Paragraph(": "));
        sectionATable.addCell(a);
        a = new Cell(1,5);
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(buktiPotong.getA_10()).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("4."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("ALAMAT"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(":  "));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell(2,5);
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(buktiPotong.getA_04()).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("8."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell(1,4);
        a.setBorder(Border.NO_BORDER);
        a.setFont(bold);
        a.setFontSize(8);
        a.add(new Paragraph("KARYAWAN ASING :"));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("     "));
        sectionATable.addCell(a);
        a = new Cell();
//        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell(1,3);
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("YA"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(""));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(""));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("  "));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
//        a = new Cell(1,5);
//        a.setBorder(Border.NO_BORDER);
//        a.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
//        a.add(new Paragraph(""));
//        a.setFontSize(10);
//        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("9."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell(1,5);
        a.setBorder(Border.NO_BORDER);
        a.setFont(bold);
        a.setFontSize(8);
        a.add(new Paragraph("KODE NEGARA DOMISILI :"));
        sectionATable.addCell(a);
        a = new Cell(1,4);
        a.setBorder(Border.NO_BORDER);
        a.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        a.add(new Paragraph(""));
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("5."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("JENIS KELAMIN"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(":  "));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell(1,16);
        a.setBorder(Border.NO_BORDER);
        Table tJenisKelamin = new Table(new float[]{15f,50f,15f,50f});
        tJenisKelamin.setFixedLayout();
        String laki = "",perempuan="";
        if(buktiPotong.getA_05()) laki = "X";
        else perempuan = "X";
        Cell tkp = new Cell();
        tkp.setFont(bold);
        tkp.setFontSize(8);
        tkp.setTextAlignment(TextAlignment.CENTER);
        tkp.add(new Paragraph(laki));
        tJenisKelamin.addCell(tkp);
        tkp = new Cell();
        tkp.setBorder(Border.NO_BORDER);
        tkp.setFont(bold);
        tkp.setFontSize(8);
        tkp.add(new Paragraph("LAKI-LAKI"));
        tJenisKelamin.addCell(tkp);
        tkp = new Cell();
        tkp.setFont(bold);
        tkp.setFontSize(8);
        tkp.setTextAlignment(TextAlignment.CENTER);
        tkp.add(new Paragraph(perempuan));
        tJenisKelamin.addCell(tkp);
        tkp = new Cell();
        tkp.setBorder(Border.NO_BORDER);
        tkp.setFont(bold);
        tkp.setFontSize(8);
        tkp.add(new Paragraph("PEREMPUAN"));
        tJenisKelamin.addCell(tkp);

        a.add(tJenisKelamin);
        sectionATable.addCell(a);
/*        a = new Cell();
//        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("LAKI-LAKI"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
//        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell(1, 13);
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("PEREMPUAN"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);*/

        sectionA.add(sectionATable);
        mainTable.addCell(sectionA);

        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph("\n"));
        p.setFont(bold);
        p.setFontSize(1);
        mainTable.addCell(p);
//        mainTable.addCell(new Cell().add(new Paragraph("").setBorder(Border.NO_BORDER)));

        Cell sectionB = new Cell();
        sectionB.setBorder(Border.NO_BORDER);
        sectionB.add(new Paragraph("B. RINCIAN PENGHASILAN DAN PERHITUNGAN PPh PASAL 21"));
        sectionB.setFont(bold);
        sectionB.setFontSize(9);
        mainTable.addCell(sectionB);

        sectionB = new Cell();
        sectionB.setBorder(Border.NO_BORDER);
        Table sectionBTable = new Table(new float[]{4f,15f,68f,30f});
        sectionBTable.setFixedLayout();
        sectionBTable.setWidth(UnitValue.createPercentValue(100));
        Cell b = new Cell(1, 3);
        b.add(new Paragraph("URAIAN"));
        b.setTextAlignment(TextAlignment.CENTER);
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("JUMLAH (Rp)"));
        b.setTextAlignment(TextAlignment.CENTER);
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1, 2);
        b.setBorderRight(Border.NO_BORDER);
        b.add(new Paragraph("KODE OBJEK PAJAK:"));
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setBorderLeft(Border.NO_BORDER);
        Table tKodePajak = new Table(new float[]{15f,50f,15f,50f});
        tKodePajak.setFixedLayout();
        tkp = new Cell();
        tkp.setFont(bold);
        tkp.setFontSize(7);
        tkp.setTextAlignment(TextAlignment.CENTER);
        tkp.add(new Paragraph("X"));
        tKodePajak.addCell(tkp);
        tkp = new Cell();
        tkp.setBorder(Border.NO_BORDER);
        tkp.setFont(bold);
        tkp.setFontSize(7);
        tkp.add(new Paragraph("21-100-01"));
        tKodePajak.addCell(tkp);
        tkp = new Cell();
        tkp.setFont(bold);
        tkp.setFontSize(7);
        tkp.setTextAlignment(TextAlignment.CENTER);
        tkp.add(new Paragraph("  "));
        tKodePajak.addCell(tkp);
        tkp = new Cell();
        tkp.setBorder(Border.NO_BORDER);
        tkp.setFont(bold);
        tkp.setFontSize(7);
        tkp.add(new Paragraph("21-100-02"));
        tKodePajak.addCell(tkp);

        b.add(tKodePajak);
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setBackgroundColor(ColorConstants.LIGHT_GRAY);
        b.add(new Paragraph("  "));
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1, 3);
        b.add(new Paragraph("PENGHASILAN BRUTO:"));
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setBackgroundColor(ColorConstants.LIGHT_GRAY);
        b.add(new Paragraph("  "));
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("1."));
//        b.setWidth(10);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("GAJI / PENSIUN ATAU THT / JHT"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setTextAlignment(TextAlignment.RIGHT);
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getB_01())));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("2."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("TUNJANGAN PPh"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setTextAlignment(TextAlignment.RIGHT);
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getB_02())));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("3."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("TUNJANGAN LAINNYA, UANG LEMBUR DAN SEBAGAINYA"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setTextAlignment(TextAlignment.RIGHT);
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getB_03())));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("4."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("HONORARIUM DAN IMBALAN LAIN SEJENISNYA"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setTextAlignment(TextAlignment.RIGHT);
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getB_04())));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("5."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("PREMI ASURANSI YANG DIBAYAR PEMBERI KERJA"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setTextAlignment(TextAlignment.RIGHT);
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getB_05())));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("6."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("PENERIMAAN DALAM BENTUK NATURA DAN KENIKMATAN LAINNYA YANG DIKENAKAN PEMOTONGAN PPh PASAL 21"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setTextAlignment(TextAlignment.RIGHT);
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getB_06())));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("7."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("TANTIEM, BONUS, GRATIFIKASI, JASA PRODUKSI DAN THR"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setTextAlignment(TextAlignment.RIGHT);
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getB_07())));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("8."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("JUMLAH PENGHASILAN BRUTO (1 S.D. 7)"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setTextAlignment(TextAlignment.RIGHT);
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getB_08())));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell(1, 3);
        b.add(new Paragraph("PENGURANGAN:"));
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("  "));
        b.setBackgroundColor(ColorConstants.LIGHT_GRAY);
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("9."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("BIAYA JABATAN / BIAYA PENSIUN"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setTextAlignment(TextAlignment.RIGHT);
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getB_09())));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("10."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("IURAN PENSIUN ATAU IURAN THT/JHT"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setTextAlignment(TextAlignment.RIGHT);
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getB_10())));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("11."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("JUMLAH PENGURANGAN (9 S.D. 10)"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setTextAlignment(TextAlignment.RIGHT);
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getB_11())));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell(1, 3);
        b.add(new Paragraph("PENGHITUNGAN PPh PASAL 21:"));
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("  "));
        b.setBackgroundColor(ColorConstants.LIGHT_GRAY);
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("12."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("JUMLAH PENGHASILAN NETO (8-11)"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setTextAlignment(TextAlignment.RIGHT);
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getB_12())));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("13."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("PENGHASILAN NETO MASA SEBELUMNYA"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setTextAlignment(TextAlignment.RIGHT);
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getB_13())));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("14."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("JUMLAH PENGHASILAN NETO UNTUK PENGHITUNGAN PPh PASAL 21 (SETAHUN/DISETAHUNKAN)"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setTextAlignment(TextAlignment.RIGHT);
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getB_14())));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("15."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("PENGHASILAN TIDAK KENA PAJAK (PTKP)"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setTextAlignment(TextAlignment.RIGHT);
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getB_15())));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("16."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("PENGHASILAN KENA PAJAK SETAHUN/DISETAHUNKAN (14-15)"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setTextAlignment(TextAlignment.RIGHT);
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getB_16())));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("17."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("PPh PASAL 21 ATAS PENGHASILAN KENA PAJAK SETAHUN/DISETAHUNKAN"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setTextAlignment(TextAlignment.RIGHT);
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getB_17())));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("18."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("PPh PASAL 21 YANG TELAH DIPOTONG MASA SEBELUMNYA"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setTextAlignment(TextAlignment.RIGHT);
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getB_18())));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("19."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("PPh PASAL 21 TERUTANG"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setTextAlignment(TextAlignment.RIGHT);
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getB_19())));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("20."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("PPh PASAL 21 DAN PPh PASAL 26 YANG TELAH DIPOTONG DAN DILUNASI"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.setTextAlignment(TextAlignment.RIGHT);
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getB_20())));
        b.setFontSize(10);
        sectionBTable.addCell(b);

        sectionB.add(sectionBTable);
        mainTable.addCell(sectionB);

        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph("\n"));
        p.setFont(bold);
        p.setFontSize(1);
        mainTable.addCell(p);
//        mainTable.addCell(new Cell().add(new Paragraph("").setBorder(Border.NO_BORDER)));

        Cell sectionC = new Cell();
        sectionC.setBorder(Border.NO_BORDER);
        sectionC.add(new Paragraph("C. IDENTITAS PEMOTONG"));
        sectionC.setFont(bold);
        sectionC.setFontSize(9);
        mainTable.addCell(sectionC);

        sectionC = new Cell();
        Table sectionCTable = new Table(new float[]{1,1,1,1,1,1,1,1,1,1,1,1,1,1,130});
        sectionCTable.setWidth(UnitValue.createPercentValue(100));
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("1."));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("NPWP:"));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("   "));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.add(new Paragraph(buktiPotong.getC_01()[0])).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        c.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("-"));
        c.setFont(bold);
        c.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.add(new Paragraph(buktiPotong.getC_01()[1])).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        c.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("."));
        c.setFont(bold);
        c.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.setFontSize(10);
        c.add(new Paragraph(buktiPotong.getC_01()[2])).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("   "));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell(1, 5);
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("3. TANGGAL & TANDA TANGAN"));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell(2, 1);
//        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("          "));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("2."));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("NAMA:"));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("   "));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell(1, 5);
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph(buktiPotong.getC_02()).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        c.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("   "));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.add(new Paragraph(buktiPotong.getC_03()[0]).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        c.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.add(new Paragraph("-"));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.add(new Paragraph(buktiPotong.getC_03()[1]).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        c.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.add(new Paragraph("-"));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.add(new Paragraph(buktiPotong.getC_03()[2]).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        c.setFontSize(10);
        sectionCTable.addCell(c);


        sectionC.add(sectionCTable);
        mainTable.addCell(sectionC);



//        BufferedReader br = new BufferedReader(new FileReader(DATA));
//        String line = br.readLine();

//        process(table, line, bold, true);
//        while ((line = br.readLine()) != null) {
//        process(table, line, font, false);
//        }
//        Table table = new Table(UnitValue.createPercentArray(new float[] { 4, 1, 3}))
//                .useAllAvailableWidth();
//        FileInputStream sr = File.OpenText(DATA);
//        String line = sr.readLine();
//        Process(table, line, bold, true);
//        while ((line = sr.ReadLine()) != null) {
//            Process(table, line, font, false);
//        }
//        sr.Close();
        document.add(mainTable);
        //Close document
        document.close();
        writer.close();
        return new File(dest);
    }

    public File createPdfNonFinal(String dest, BuktiPotong buktiPotong, Integer userId) throws IOException {
        //Initialize PDF writer
        PdfWriter writer = new PdfWriter(dest);
        //Initialize PDF document
        PdfDocument pdf = new PdfDocument(writer);
        // Initialize document
        PageSize pageSize = PageSize.LEGAL;
        Document document = new Document(pdf, pageSize);
        document.setMargins(20, 20, 20, 20);
        PdfFont font = PdfFontFactory.createFont(StandardFonts.HELVETICA);
        PdfFont bold = PdfFontFactory.createFont(StandardFonts.HELVETICA_BOLD);

        Table mainTable = new Table(new float[]{1});
        mainTable.setWidth(UnitValue.createPercentValue(100));

        Cell s = new Cell();
        s.setBorder(Border.NO_BORDER);
        Table stable = new Table(new float[]{4,100,4});
        stable.setFixedLayout();
        stable.setWidth(UnitValue.createPercentValue(100));
        Cell x = new Cell();
        x.setHeight(4);
        x.add(new Paragraph(" "));
        x.setBackgroundColor(ColorConstants.BLACK);
        stable.addCell(x);
        x = new Cell();
        x.setBorder(Border.NO_BORDER);
        x.setBorderTop(new DottedBorder(1f));
        stable.addCell(x);
        x = new Cell();
        x.add(new Paragraph(" "));
        x.setBackgroundColor(ColorConstants.BLACK);
        stable.addCell(x);
        s.add(stable);
        mainTable.addCell(s);

        Cell h = new Cell();
        h.setBorder(Border.NO_BORDER);
        Table headerTable = new Table(new float[]{60,100,50});
        headerTable.setFixedLayout();
        headerTable.setWidth(UnitValue.createPercentValue(100));
        Cell c = new Cell(4,1);
        c.setBorderTop(Border.NO_BORDER);
        c.setBorderLeft(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.setHorizontalAlignment(HorizontalAlignment.CENTER);
        c.setVerticalAlignment(VerticalAlignment.MIDDLE);
        c.setFont(bold);
        c.setFontSize(9);
        c.add(new Image(ImageDataFactory.create("/logo_drijen_pajak.png")).scaleToFit(70,70).setTextAlignment(TextAlignment.CENTER).setHorizontalAlignment(HorizontalAlignment.CENTER));
        c.add(new Paragraph("\nKEMENTERIAN KEUANGAN RI DIREKTORAT JENDERAL PAJAK"));
        headerTable.addCell(c);
        c = new Cell(3,1);
        c.setTextAlignment(TextAlignment.CENTER);
        c.setBorderTop(Border.NO_BORDER);
        c.setFont(bold);
        c.setFontSize(11);
        c.add(new Paragraph("BUKTI PEMOTONGAN PAJAK PENGHASILAN PASAL 21 (TIDAK FINAL) ATAU PASAL 26\n\n"));
        headerTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.RIGHT);
        c.setHorizontalAlignment(HorizontalAlignment.RIGHT);
        Table dum = new Table(new float[]{15,1,15,1,15,1,15});
        dum.setHorizontalAlignment(HorizontalAlignment.RIGHT);
        dum.setFixedLayout();
        Cell d = new Cell();
        d.add(new Paragraph("  "));
        d.setHeight(10);
        dum.addCell(d);
        d = new Cell();
        d.setBorder(Border.NO_BORDER);
        d.add(new Paragraph(""));
        dum.addCell(d);
        d = new Cell();
        d.add(new Paragraph("  "));
        d.setBackgroundColor(ColorConstants.BLACK);
        dum.addCell(d);
        d = new Cell();
        d.setBorder(Border.NO_BORDER);
        d.add(new Paragraph(""));
        dum.addCell(d);
        d = new Cell();
        d.add(new Paragraph("  "));
        dum.addCell(d);
        d = new Cell();
        d.setBorder(Border.NO_BORDER);
        d.add(new Paragraph(""));
        dum.addCell(d);
        d = new Cell();
        d.add(new Paragraph("  "));
        d.setBackgroundColor(ColorConstants.BLACK);
        dum.addCell(d);
        c.add(dum);
        headerTable.addCell(c);
        c = new Cell();
        c.setFont(bold);
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.RIGHT);
        c.add(new Paragraph("FORMULIR 1721 - VI"));
        headerTable.addCell(c);
        c = new Cell();
        c.setFontSize(7);
        c.setHorizontalAlignment(HorizontalAlignment.RIGHT);
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("Lembar ke-1 : untuk Penerima Penghasilan").setFirstLineIndent(30));
        c.add(new Paragraph("Lembar ke-2 : untuk Pemotong").setFirstLineIndent(30));
        headerTable.addCell(c);
        c = new Cell(1,3);
        c.setFont(bold);
        c.setVerticalAlignment(VerticalAlignment.MIDDLE);
        c.setTextAlignment(TextAlignment.JUSTIFIED);
//        c.add(new Paragraph("NOMOR :    1 . 3 - 12 . 19 - "+String.format("%07d", userId)).setFirstLineIndent(20));
        c.add(new Paragraph("NOMOR :    1 . 3 - 12 . 19 - "+buktiPotong.getH_01()).setFirstLineIndent(20));
        c.setFontSize(15);
        headerTable.addCell(c);

        h.add(headerTable);
        mainTable.addCell(h);

        Cell p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph("\n"));
        p.setFont(bold);
        p.setFontSize(1);
        mainTable.addCell(p);

        Cell sectionA = new Cell();
        sectionA.setBorder(Border.NO_BORDER);
        sectionA.add(new Paragraph("A. IDENTITAS PENERIMA PENGHASILAN YANG DIPOTONG"));
        sectionA.setFont(bold);
        sectionA.setFontSize(9);
        mainTable.addCell(sectionA);

        sectionA = new Cell();
        Table sectionATable = new Table(new float[]{4,40,4,10,30,10,4,40,4,40});
        sectionATable.setFixedLayout();
        sectionATable.setWidth(UnitValue.createPercentValue(100));
        Cell a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("1."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("NPWP"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(":  "));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell(1,2);
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(buktiPotong.getA_01()).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("2."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.setFont(bold);
        a.setFontSize(8);
        a.add(new Paragraph("NIK / NO. PASPOR"));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(":  "));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(buktiPotong.getA_02()).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("3."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("NAMA"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(":  "));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell(1,7);
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(buktiPotong.getA_03()).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("4."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("ALAMAT"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(":  "));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell(2,7);
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(buktiPotong.getA_04()).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell(1,3);
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(" "));
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("5."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("WAJIB PAJAK LUAR NEGERI"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(":  "));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
//        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("YA"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("6."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("KODE NEGARA DOMISILI"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(":  "));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        a.add(new Paragraph(""));
        a.setFontSize(10);
        sectionATable.addCell(a);

        sectionA.add(sectionATable);
        mainTable.addCell(sectionA);

        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph("\n"));
        p.setFont(bold);
        p.setFontSize(1);
        mainTable.addCell(p);

        Cell sectionB = new Cell();
        sectionB.setBorder(Border.NO_BORDER);
        sectionB.add(new Paragraph("B. PPh PASAL 21 DAN/ATAU PASAL 26 YANG DIPOTONG"));
        sectionB.setFont(bold);
        sectionB.setFontSize(9);
        mainTable.addCell(sectionB);

        sectionB = new Cell();
        sectionB.setBorder(Border.NO_BORDER);
        Table sectionBTable = new Table(new float[]{20f,15f,30f,15f,10f,30f});
        sectionBTable.setFixedLayout();
        sectionBTable.setWidth(UnitValue.createPercentValue(100));
        Cell b = new Cell();
        b.add(new Paragraph("KODE OBJEK PAJAK"));
        b.setTextAlignment(TextAlignment.CENTER);
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("JUMLAH PENGHASILAN BRUTO (Rp)"));
        b.setTextAlignment(TextAlignment.CENTER);
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("DASAR PENGENAAN PAJAK (Rp)"));
        b.setTextAlignment(TextAlignment.CENTER);
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("TARIF LEBIH TINGGI 20% (TIDAK BER-NPWP)"));
        b.setTextAlignment(TextAlignment.CENTER);
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("TARIF (%)"));
        b.setTextAlignment(TextAlignment.CENTER);
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("PPh DIPOTONG (Rp)"));
        b.setTextAlignment(TextAlignment.CENTER);
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("(1)"));
        b.setBackgroundColor(ColorConstants.LIGHT_GRAY);
        b.setTextAlignment(TextAlignment.CENTER);
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("(2)"));
        b.setBackgroundColor(ColorConstants.LIGHT_GRAY);
        b.setTextAlignment(TextAlignment.CENTER);
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("(3)"));
        b.setBackgroundColor(ColorConstants.LIGHT_GRAY);
        b.setTextAlignment(TextAlignment.CENTER);
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("(4)"));
        b.setBackgroundColor(ColorConstants.LIGHT_GRAY);
        b.setTextAlignment(TextAlignment.CENTER);
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("(5)"));
        b.setBackgroundColor(ColorConstants.LIGHT_GRAY);
        b.setTextAlignment(TextAlignment.CENTER);
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("(6)"));
        b.setBackgroundColor(ColorConstants.LIGHT_GRAY);
        b.setTextAlignment(TextAlignment.CENTER);
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("21 - 100 - "+buktiPotong.getKode_pajak()));
        b.setTextAlignment(TextAlignment.CENTER);
        b.setFont(bold);
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getBruto())));
        b.setTextAlignment(TextAlignment.RIGHT);
        b.setFont(bold);
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getDpp())));
        b.setTextAlignment(TextAlignment.RIGHT);
        b.setFont(bold);
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        Table tableNpwpBox = new Table(new float[]{4});
        tableNpwpBox.setFixedLayout();
        Cell b1 = new Cell();
        b1.setTextAlignment(TextAlignment.CENTER);
        b1.setFont(bold);
        b1.setFontSize(10);
        if(buktiPotong.getTdk_npwp())
            b1.add(new Paragraph(" X "));
        else
            b1.add(new Paragraph("   "));
        tableNpwpBox.addCell(b1);
        tableNpwpBox.setTextAlignment(TextAlignment.CENTER);
        tableNpwpBox.setHorizontalAlignment(HorizontalAlignment.CENTER);
        tableNpwpBox.setVerticalAlignment(VerticalAlignment.MIDDLE);
        b.setTextAlignment(TextAlignment.CENTER);
        b.setHorizontalAlignment(HorizontalAlignment.CENTER);
        b.setVerticalAlignment(VerticalAlignment.MIDDLE);
        b.add(tableNpwpBox);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph(buktiPotong.getTarif().toString()));
        b.setTextAlignment(TextAlignment.CENTER);
        b.setFont(bold);
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph(kursIndonesia.format(buktiPotong.getPph_dipotong())));
        b.setTextAlignment(TextAlignment.RIGHT);
        b.setFont(bold);
        b.setFontSize(10);
        sectionBTable.addCell(b);

        sectionB.add(sectionBTable);
        mainTable.addCell(sectionB);

        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph("\n"));
        p.setFont(bold);
        p.setFontSize(1);
        mainTable.addCell(p);

        Cell sectionC = new Cell();
        sectionC.setBorder(Border.NO_BORDER);
        sectionC.add(new Paragraph("C. IDENTITAS PEMOTONG"));
        sectionC.setFont(bold);
        sectionC.setFontSize(9);
        mainTable.addCell(sectionC);

        sectionC = new Cell();
        Table sectionCTable = new Table(new float[]{1,1,1,1,1,1,1,1,1,1,1,1,1,1,130});
        sectionCTable.setWidth(UnitValue.createPercentValue(100));
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("1."));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("NPWP:"));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("   "));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.add(new Paragraph(buktiPotong.getH_03()[0])).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        c.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("-"));
        c.setFont(bold);
        c.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.add(new Paragraph(buktiPotong.getH_03()[1])).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        c.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("."));
        c.setFont(bold);
        c.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.setFontSize(10);
        c.add(new Paragraph(buktiPotong.getH_03()[2])).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("   "));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell(1, 5);
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("3. TANGGAL & TANDA TANGAN"));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell(2, 1);
        c.add(new Paragraph("          "));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("2."));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("NAMA:"));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("   "));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell(1, 5);
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph(buktiPotong.getH_04()).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        c.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("   "));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.add(new Paragraph(buktiPotong.getC_03()[0]).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        c.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.add(new Paragraph("-"));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.add(new Paragraph(buktiPotong.getC_03()[1]).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        c.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.add(new Paragraph("-"));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.setTextAlignment(TextAlignment.CENTER);
        c.add(new Paragraph(buktiPotong.getC_03()[2]).setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        c.setFontSize(10);
        sectionCTable.addCell(c);

        sectionC.add(sectionCTable);
        mainTable.addCell(sectionC);

        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph("\n"));
        p.setFont(bold);
        p.setFontSize(1);
        mainTable.addCell(p);

        Cell ket = new Cell();
        Table sectionKet = new Table(new float[]{4f, 10f, 100f});
        sectionKet.setFixedLayout();
        sectionKet.setWidth(UnitValue.createPercentValue(100));
        Cell k = new Cell(1,3);
        k.setTextAlignment(TextAlignment.CENTER);
        k.setBackgroundColor(ColorConstants.LIGHT_GRAY);
        k.add(new Paragraph("KODE OBJEK PAJAK PENGHASILAN PASAL 21 (TIDAK FINAL) ATAU PASAL 26"));
        k.setFont(bold);
        k.setFontSize(8);
        sectionKet.addCell(k);
        k = new Cell (1,3);
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph(" "));
        sectionKet.addCell(k);
        k = new Cell ();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph(" "));
        sectionKet.addCell(k);
        k = new Cell(1,2);
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("PPh PASAL 21 TIDAK FINAL"));
        k.setFont(bold);
        k.setFontSize(7);
        sectionKet.addCell(k);
        k = new Cell ();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("1."));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("21-100-03"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("Upah Pegawai Tidak Tetap atau Tenaga Kerja Lepas"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell ();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("2."));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("21-100-04"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("Imbalan Kepada Distributor Multi Level Marketing (MLM)"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell ();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("3."));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("21-100-05"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("Imbalan Kepada Petugas Dinas Luar Asuransi"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell ();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("4."));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("21-100-06"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("Imbalan Kepada Penjaja Barang Dagangan"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell ();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("5."));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("21-100-07"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("Imbalan Kepada Tenaga Ahli"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell ();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("6."));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("21-100-08"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("Imbalan Kepada Bukan Pegawai yang Menerima Penghasilan yang Bersifat Berkesinambungan"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell ();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("7."));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("21-100-09"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("Imbalan Kepada Bukan Pegawai yang Menerima Penghasilan yang Tidak Bersifat Berkesinambungan"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell ();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("8."));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("21-100-10"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("Honorarium atau Imbalan Kepada Anggota Dewan Komisaris atau Dewan Pengawas yang tidak Merangkap sebagai Pegawai Tetap"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell ();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("9."));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("21-100-11"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("Jasa Produksi, Tantiem, Bonus atau Imbalan Kepada Mantan Pegawai"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell ();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("10."));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("21-100-12"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("Penarikan Dana Pensiun oleh Pegawai"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell ();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("11."));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("21-100-13"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("Imbalan Kepada Peserta Kegiatan"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell ();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("12."));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("21-100-99"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("Objek PPh Pasal 21 Tidak Final Lainnya"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell(1,3);
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph(" "));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell ();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph(" "));
        sectionKet.addCell(k);
        k = new Cell(1,2);
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("PPh PASAL 26"));
        k.setFont(bold);
        k.setFontSize(7);
        sectionKet.addCell(k);
        k = new Cell ();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("1."));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("27-100-99"));
        k.setFontSize(5);
        sectionKet.addCell(k);
        k = new Cell();
        k.setBorder(Border.NO_BORDER);
        k.add(new Paragraph("Imbalan sehubung dengan jasa, pekerjaan dan kegiatan, hadiah dan penghargaan, pensiun dan pembayaran berkala lainnya yang dipotong PPh Pasal 26"));
        k.setFontSize(5);
        sectionKet.addCell(k);

        ket.add(sectionKet);
        mainTable.addCell(ket);

        document.add(mainTable);
        //Close document
        document.close();
        writer.close();
        return new File(dest);
    }
}
