package usu.pajak.fariz.service;

import com.itextpdf.io.font.constants.StandardFonts;
import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.geom.Rectangle;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.ColumnDocumentRenderer;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.borders.Border;
import com.itextpdf.layout.borders.SolidBorder;
import com.itextpdf.layout.element.*;
import com.itextpdf.layout.property.TextAlignment;
import com.itextpdf.layout.property.UnitValue;

import java.io.*;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.StringTokenizer;
import java.util.stream.Stream;

import static com.itextpdf.html2pdf.html.AttributeConstants.DATA;

public class PdfBuktiPotong {

    public static void main(String[] args) throws IOException {
        new PdfBuktiPotong().createPdf("/test7.pdf");
    }

    private void assignToObject(){

    }

    public void createPdf(String dest) throws IOException {
        //Initialize PDF writer
        PdfWriter writer = new PdfWriter(dest);
        //Initialize PDF document
        PdfDocument pdf = new PdfDocument(writer);
        // Initialize document
        PageSize pageSize = PageSize.LEGAL;
        Document document = new Document(pdf, pageSize);
        document.setMargins(20, 20, 20, 20);
        PdfFont font = PdfFontFactory.createFont(StandardFonts.HELVETICA);
        PdfFont bold = PdfFontFactory.createFont(StandardFonts.HELVETICA_BOLD);
        /*//Set column parameters
        float offSet = 36;
        float columnWidth = (pageSize.getWidth() - offSet * 2 + 10) / 3;
        float columnHeight = pageSize.getHeight() - offSet * 2;;

        //Define column areas
        Rectangle[] columns = {
                new Rectangle(offSet - 5, offSet, columnWidth, 400),
                new Rectangle(offSet + columnWidth, offSet, columnWidth, 400),
                new Rectangle(offSet + columnWidth * 2 + 5, offSet, columnWidth, 400)};
        document.setRenderer(new ColumnDocumentRenderer(document, columns));
        Paragraph p1 = new Paragraph("KEMENTERIAN KEUANGAN RI DIREKTORAT JENDERAL PAJAK")
                .setFont(font)
                .setFontSize(14);
        Image image = new Image(ImageDataFactory.create("/foto.png")).scaleToFit(100,100);
        document.add(image);
        document.add(p1);
        document.add(new Paragraph("BUKTI PEMOTONGAN PAJAK PENGHASILAN PASAL 21 BAGI PEGAWAI TETAP ATAU PENERIMA PENSIUN ATAU TUNJANGAN HARI TUA/JAMINAN HARI TUA BERKALA"));
*/
        /*Image image = new Image(ImageDataFactory.create("/foto.png")).scaleToFit(100,100);
        Table table = new Table(new float[]{3, 3, 3,3});
        table.setWidth(UnitValue.createPercentValue(100));
        Cell c1 = new Cell();
        c1.add(image);
        c1.add(new Paragraph("KEMENTERIAN KEUANGAN RI DIREKTORAT JENDERAL PAJAK"));
        table.addCell(c1);
        Cell c2 = new Cell();
        c2.add(new Paragraph("BUKTI PEMOTONGAN PAJAK PENGHASILAN PASAL 21 BAGI PEGAWAI TETAP ATAU PENERIMA PENSIUN ATAU TUNJANGAN HARI TUA/JAMINAN HARI TUA BERKALA"));
        table.addCell(c2);
        Cell c3 = new Cell(2,2);
        c3.add(new Paragraph("NOMOR: 1 . 1 - 12____ . 18____ - ____________"));
        table.addCell(c3);*/

        Table mainTable = new Table(new float[]{1});
        mainTable.setWidth(UnitValue.createPercentValue(100));

        Cell pemotong = new Cell();
        Table pemotongTable = new Table(new float[]{1,1,4,1,3,1,3,5});
//        pemotongTable.setWidth(UnitValue.createPercentValue(100));
        Cell p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph("NPWP PEMOTONG"));
        p.setFont(bold);
        p.setFontSize(8);
        pemotongTable.addCell(p);
        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph(":   "));
        p.setFont(bold);
        p.setFontSize(8);
        pemotongTable.addCell(p);
        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        p.add(new Paragraph("99999999999"));
        p.setFontSize(10);
        pemotongTable.addCell(p);
        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph("-"));
        p.setWidth(3);
        p.setFont(bold);
        p.setFontSize(8);
        pemotongTable.addCell(p);
        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        p.setWidth(100);
        p.add(new Paragraph("121"));
        p.setFontSize(10);
        pemotongTable.addCell(p);
        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph("."));
        p.setWidth(3);
        p.setFont(bold);
        p.setFontSize(8);
        pemotongTable.addCell(p);
        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        p.add(new Paragraph("000"));
        p.setFontSize(10);
        pemotongTable.addCell(p);
        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph(""));
        pemotongTable.addCell(p);
        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph("NAMA PEMOTONG"));
        p.setFont(bold);
        p.setFontSize(8);
        pemotongTable.addCell(p);
        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph(":   "));
        p.setFont(bold);
        p.setFontSize(8);
        pemotongTable.addCell(p);
        p = new Cell(1,6);
        p.setBorder(Border.NO_BORDER);
        p.setWidth(450);
        p.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        p.add(new Paragraph("UNIVERSITAS SUMATERA UTARA"));
        p.setFontSize(10);
        pemotongTable.addCell(p);

        pemotong.add(pemotongTable);
        mainTable.addCell(pemotong);

        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph("\n"));
        p.setFont(bold);
        p.setFontSize(1);
        mainTable.addCell(p);
//        mainTable.addCell(new Cell().add(new Paragraph("").setBorder(Border.NO_BORDER)));

        Cell sectionA = new Cell();
        sectionA.setBorder(Border.NO_BORDER);
        sectionA.add(new Paragraph("A. IDENTITAS PENERIMA PENGHASILAN YANG DIPOTONG"));
        sectionA.setFont(bold);
        sectionA.setFontSize(9);
        mainTable.addCell(sectionA);

        sectionA = new Cell();
        Table sectionATable = new Table(new float[]{1,2,1,3,1,2,1,2,1,1,1,2,1,1,2,1,1,2,3});
        Cell a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("1."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("NPWP"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(":  "));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
//        a.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        a.add(new Paragraph("00.000.000.0     ").setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
//        a.setFont(bold);
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("-"));
        a.setFont(bold);
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
//        a.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        a.add(new Paragraph("121    ").setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
//        a.setFont(bold);
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("."));
        a.setFont(bold);
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
//        a.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        a.add(new Paragraph("000").setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
//        Text text1 = new Text("000");
//        text1.setUnderline(1f, -3);
//        a.add(new Paragraph(text1));
//        a.setFont(bold);
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("6."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell(1,9);
        a.setBorder(Border.NO_BORDER);
        a.setFont(bold);
        a.setFontSize(8);
        a.add(new Paragraph("STATUS / JUMLAH TANGGUNGAN KELUARGA UNTUK PTKP"));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("2."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("NIK /NO. PASPOR"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(":  "));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell(1,5);
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("000000000").setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(""));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("K/"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("0 ").setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("TK/"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("0 ").setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("HB/"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("0 ").setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("3."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("NAMA"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(":  "));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell(1,5);
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("Agus").setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("7."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell(1,3);
        a.setBorder(Border.NO_BORDER);
        a.setFont(bold);
        a.setFontSize(8);
        a.add(new Paragraph("NAMA JABATAN :"));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell(1,5);
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("Pegawai").setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("4."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("ALAMAT"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(":  "));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell(1,5);
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("Medan").setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("8."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell(1,4);
        a.setBorder(Border.NO_BORDER);
        a.setFont(bold);
        a.setFontSize(8);
        a.add(new Paragraph("KARYAWAN ASING :"));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("     "));
        sectionATable.addCell(a);
        a = new Cell();
//        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell(1,3);
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("YA"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(""));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(""));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("  "));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell(1,5);
        a.setBorder(Border.NO_BORDER);
        a.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        a.add(new Paragraph(""));
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("9."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell(1,5);
        a.setBorder(Border.NO_BORDER);
        a.setFont(bold);
        a.setFontSize(8);
        a.add(new Paragraph("KODE NEGARA DOMISILI :"));
        sectionATable.addCell(a);
        a = new Cell(1,4);
        a.setBorder(Border.NO_BORDER);
        a.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        a.add(new Paragraph(""));
        a.setFontSize(10);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("5."));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("JENIS KELAMIN"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph(":  "));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
//        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell();
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("LAKI-LAKI"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);
        a = new Cell();
//        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("   "));
        sectionATable.addCell(a);
        a = new Cell(1, 13);
        a.setBorder(Border.NO_BORDER);
        a.add(new Paragraph("PEREMPUAN"));
        a.setFont(bold);
        a.setFontSize(8);
        sectionATable.addCell(a);

        sectionA.add(sectionATable);
        mainTable.addCell(sectionA);

        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph("\n"));
        p.setFont(bold);
        p.setFontSize(1);
        mainTable.addCell(p);
//        mainTable.addCell(new Cell().add(new Paragraph("").setBorder(Border.NO_BORDER)));

        Cell sectionB = new Cell();
        sectionB.setBorder(Border.NO_BORDER);
        sectionB.add(new Paragraph("B. RINCIAN PENGHASILAN DAN PERHITUNGAN PPh PASAL 21"));
        sectionB.setFont(bold);
        sectionB.setFontSize(9);
        mainTable.addCell(sectionB);

        sectionB = new Cell();
        sectionB.setBorder(Border.NO_BORDER);
        Table sectionBTable = new Table(new float[]{1f,50f,50f,30f});
//        sectionBTable.set
//        sectionBTable.setWidth(UnitValue)
        sectionBTable.setWidth(UnitValue.createPercentValue(100));
        Cell b = new Cell(1, 3);
        b.add(new Paragraph("URAIAN"));
        b.setTextAlignment(TextAlignment.CENTER);
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("JUMLAH (Rp)"));
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1, 2);
        b.add(new Paragraph("KODE OBJECK PAJAK:"));
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("  "));
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("  "));
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1, 3);
        b.add(new Paragraph("PENGHASILAN BRUTO:"));
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("  "));
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("1."));
//        b.setWidth(10);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("GAJI / PENSIUN ATAU THT / JHT"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("700.000.000"));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("2."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("TUNJANGAN PPh"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("0"));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("3."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("TUNJANGAN LAINNYA, UANG LEMBUR DAN SEBAGAINYA"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("0"));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("4."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("HONORARIUM DAN IMBALAN LAIN SEJENISNYA"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("0"));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("5."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("PREMI ASURANSI YANG DIBAYAR PEMBERI KERJA"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("0"));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("6."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("PENERIMAAN DALAM BENTUK NATURA DAN KENIKMATAN LAINNYA YANG DIKENAKAN PEMOTONGAN PPh PASAL 21"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("0"));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("7."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("TANTIEM, BONUS, GRATIFIKASI, JASA PRODUKSI DAN THR"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("0"));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("8."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("JUMLAH PENGHASILAN BRUTO (1 S.D. 7)"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("0"));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell(1, 3);
        b.add(new Paragraph("PENGURANGAN:"));
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("  "));
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("9."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("BIAYA JABATAN / BIAYA PENSIUN"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("0"));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("10."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("IURAN PENSIUN ATAU IURAN THT/JHT"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("0"));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("11."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("JUMLAH PENGURANGAN (9 S.D. 10)"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("0"));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell(1, 3);
        b.add(new Paragraph("PENGHITUNGAN PPh PASAL 21:"));
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("  "));
        b.setFont(bold);
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("12."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("JUMLAH PENGHASILAN NETO (8-11)"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("0"));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("13."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("PENGHASILAN NETO MASA SEBELUMNYA"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("0"));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("14."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("JUMLAH PENGHASILAN NETO UNTUK PENGHITUNGAN PPh PASAL 21 (SETAHUN/DISETAHUNKAN)"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("0"));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("15."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("PENGHASILAN TIDAK KENA PAJAK (PTKP)"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("0"));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("16."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("PENGHASILAN KENA PAJAK SETAHUN/DISETAHUNKAN (14-15)"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("0"));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("17."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("PPh PASAL 21 ATAS PENGHASILAN KENA PAJAK SETAHUN/DISETAHUNKAN"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("0"));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("18."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("PPh PASAL 21 YANG TELAH DIPOTONG MASA SEBELUMNYA"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("0"));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("19."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("PPh PASAL 21 TERUTANG"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("0"));
        b.setFontSize(10);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("20."));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell(1,2);
        b.add(new Paragraph("PPh PASAL 21 DAN PPh PASAL 26 YANG TELAH DIPOTONG DAN DILUNASI"));
        b.setFontSize(8);
        sectionBTable.addCell(b);
        b = new Cell();
        b.add(new Paragraph("0"));
        b.setFontSize(10);
        sectionBTable.addCell(b);

        sectionB.add(sectionBTable);
        mainTable.addCell(sectionB);

        p = new Cell();
        p.setBorder(Border.NO_BORDER);
        p.add(new Paragraph("\n"));
        p.setFont(bold);
        p.setFontSize(1);
        mainTable.addCell(p);
//        mainTable.addCell(new Cell().add(new Paragraph("").setBorder(Border.NO_BORDER)));

        Cell sectionC = new Cell();
        sectionC.setBorder(Border.NO_BORDER);
        sectionC.add(new Paragraph("C. IDENTITAS PEMOTONG"));
        sectionC.setFont(bold);
        sectionC.setFontSize(9);
        mainTable.addCell(sectionC);

        sectionC = new Cell();
//        sectionC.setBorder(Border.NO_BORDER);
        Table sectionCTable = new Table(new float[]{1,1,1,1,1,1,1,1,1,1,1,1,1,1,1});
        sectionCTable.setWidth(UnitValue.createPercentValue(100));
        Cell c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("1."));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("NPWP:"));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("   "));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
//        a.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        c.add(new Paragraph("00.000.000.0     ").setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
//        a.setFont(bold);
        c.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("-"));
        c.setFont(bold);
        c.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
//        a.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        c.add(new Paragraph("121    ").setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
//        a.setFont(bold);
        c.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("."));
        c.setFont(bold);
        c.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
//        a.setBorderBottom(new SolidBorder(ColorConstants.BLACK,1));
        c.add(new Paragraph("000").setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
//        Text text1 = new Text("000");
//        text1.setUnderline(1f, -3);
//        a.add(new Paragraph(text1));
//        a.setFont(bold);
        a.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("   "));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell(1, 5);
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("3. TANGGAL & TANDA TANGAN"));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell(2, 1);
//        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("          "));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("2."));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("NAMA:"));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("   "));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell(1, 5);
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("AHMAD IKBAL").setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        c.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("   "));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph(" 12 ").setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        c.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("-"));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph(" 20 ").setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        c.setFontSize(10);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph("-"));
        c.setFont(bold);
        c.setFontSize(8);
        sectionCTable.addCell(c);
        c = new Cell();
        c.setBorder(Border.NO_BORDER);
        c.add(new Paragraph(" 2020 ").setBorderBottom(new SolidBorder(ColorConstants.BLACK,1)));
        c.setFontSize(10);
        sectionCTable.addCell(c);


        sectionC.add(sectionCTable);
        mainTable.addCell(sectionC);



//        BufferedReader br = new BufferedReader(new FileReader(DATA));
//        String line = br.readLine();

//        process(table, line, bold, true);
//        while ((line = br.readLine()) != null) {
//        process(table, line, font, false);
//        }
//        Table table = new Table(UnitValue.createPercentArray(new float[] { 4, 1, 3}))
//                .useAllAvailableWidth();
//        FileInputStream sr = File.OpenText(DATA);
//        String line = sr.readLine();
//        Process(table, line, bold, true);
//        while ((line = sr.ReadLine()) != null) {
//            Process(table, line, font, false);
//        }
//        sr.Close();
        document.add(mainTable);
        //Close document
        document.close();
    }

    public void process(Table table, String line, PdfFont font, boolean isHeader) {
        StringTokenizer tokenizer = new StringTokenizer(line, ";");
        while (tokenizer.hasMoreTokens()) {
            if (isHeader) {
                table.addHeaderCell(
                        new Cell().add(
                                new Paragraph(tokenizer.nextToken()).setFont(font)));
            } else {
                table.addCell(
                        new Cell().add(
                                new Paragraph(tokenizer.nextToken()).setFont(font)));
            }
        }
    }

//    public void export() throws DocumentException, IOException, URISyntaxException {
//        Document document = new Document();
////        document.
//        PdfWriter.getInstance(document, new FileOutputStream("/iTextHelloWorld.pdf"));
//
//        document.open();
//        Font font = FontFactory.getFont(FontFactory.COURIER, 16, BaseColor.BLACK);
////        Chunk chunk = new Chunk("Hello World", font);
//        PdfPTable table = new PdfPTable(3);
////        table.
//        addTableHeader(table);
//        addRows(table);
//        addCustomRows(table);
//
//        document.add(table);
//
////        document.add(chunk);
//        document.close();
//    }
//
//    private void addTableHeader(PdfPTable table) {
//        Stream.of("column header 1", "column header 2", "column header 3")
//                .forEach(columnTitle -> {
//                    PdfPCell header = new PdfPCell();
//                    header.setBackgroundColor(BaseColor.LIGHT_GRAY);
//                    header.setBorderWidth(2);
//                    header.setPhrase(new Phrase(columnTitle));
//                    table.addCell(header);
//                });
//    }
//
//    private void addRows(PdfPTable table) {
//        table.addCell("row 1, col 1");
//        table.addCell("row 1, col 2");
//        table.addCell("row 1, col 3");
//    }
//
//    private void addCustomRows(PdfPTable table)
//            throws URISyntaxException, BadElementException, IOException {
////        Path path = Paths.get(ClassLoader.getSystemResource("D:/foto.png").toURI());
////        Path path = Paths.get(new URI("/foto.png"));
//        Image img = Image.getInstance(new File("/foto.png").getAbsolutePath());
//        img.scalePercent(10);
//
//        PdfPCell imageCell = new PdfPCell(img);
//        table.addCell(imageCell);
//
//        PdfPCell horizontalAlignCell = new PdfPCell(new Phrase("row 2, col 2"));
//        horizontalAlignCell.setHorizontalAlignment(Element.ALIGN_CENTER);
//        table.addCell(horizontalAlignCell);
//
//        PdfPCell verticalAlignCell = new PdfPCell(new Phrase("row 2, col 3"));
//        verticalAlignCell.setVerticalAlignment(Element.ALIGN_BOTTOM);
//        table.addCell(verticalAlignCell);
//    }
}
